"""The internal contract between the API and this service (docs/phase2/10, "API <-> Python contract").

    python -m app.contract            writes ../../contracts/ai-internal.openapi.json
    python -m app.contract --check    exits 1 if the committed file differs from the code

It is FastAPI's description of the routes, plus, on every operation, `x-action` (the service-token
action it requires) and `x-subject` (the path parameter the token must be bound to, if any). The API
reads the same file: its client may only call operations listed here, with the action listed here.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from fastapi.routing import APIRoute

from app.main import create_app

CONTRACT = Path(__file__).resolve().parents[3] / "contracts" / "ai-internal.openapi.json"


def build() -> dict[str, Any]:
    app = create_app()
    doc = app.openapi()
    doc["info"]["description"] = "Internal contract between the LegacyAI API and the AI service. Generated by services/ai/app/contract.py."
    for route in app.routes:
        if not isinstance(route, APIRoute) or not route.path.startswith("/internal/"):
            continue
        marks: list[Any] = [d.call for d in route.dependant.dependencies if hasattr(d.call, "legacyai_action")]
        if len(marks) != 1:
            raise RuntimeError(f"{route.path}: every internal route needs exactly one service-token check")
        for method in route.methods or set():
            op = doc["paths"][route.path][method.lower()]
            op["x-action"] = marks[0].legacyai_action
            op["x-subject"] = marks[0].legacyai_subject
    return doc


def render() -> str:
    return json.dumps(build(), indent=2, sort_keys=True) + "\n"


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        current = CONTRACT.read_text(encoding="utf-8") if CONTRACT.exists() else ""
        if current != text:
            print("ai-contract: contracts/ai-internal.openapi.json is out of date - run: python -m app.contract")
            sys.exit(1)
        print(f"ai-contract: PASS ({len(json.loads(text)['paths'])} internal paths match the code)")
    else:
        CONTRACT.parent.mkdir(parents=True, exist_ok=True)
        CONTRACT.write_text(text, encoding="utf-8", newline="\n")
        print(f"ai-contract: wrote {CONTRACT}")
