// GENERATED by scripts/generate-api.mjs from services/api/openapi.yaml. Do not edit by hand.
// Run `npm run generate` after the contract changes; CI fails if this file is out of date.
/* eslint-disable */

export interface KSource {
  id: string;
  kind: "document" | "interview";
  title: string;
  department_id: string | null;
  sensitivity: number;
  contributor_person_id: string | null;
  company_document: boolean;
  status: string;
  failure_code: string | null;
  mime: string | null;
  byte_size: number | null;
  page_count: number | null;
  chunk_count: number;
  created_at: string;
  ready_at: string | null;
}

export interface KSourceDetail {
  id: string;
  kind: "document" | "interview";
  title: string;
  department_id: string | null;
  sensitivity: number;
  contributor_person_id: string | null;
  company_document: boolean;
  status: string;
  failure_code: string | null;
  mime: string | null;
  byte_size: number | null;
  page_count: number | null;
  chunk_count: number;
  created_at: string;
  ready_at: string | null;
  redactions: {
    type: string;
    count: number;
    low_confidence: number;
  }[];
}

export interface KSourceCreated {
  id: string;
  status: string;
  title: string;
}

export interface KUploadResult {
  status: "ready" | "processing" | "failed";
  failure_code: string | null;
  chunk_count: number | null;
  pending_chunks: number | null;
  duplicate_of: string | null;
}

export interface KStatus {
  id: string;
  status: string;
}

export interface KSourceWithdrawn {
  id: string;
  status: string;
  items_withdrawn: number;
  items_back_in_review: number;
}

export interface KLabelResult {
  id: string;
  rows: number;
}

export interface KCitation {
  ref: string;
  kind: "item" | "source";
  id: string;
  title: string;
  snippet: string;
  verification_status: string;
  expert_display_name: string | null;
  derived_from: {
    source_id: string;
    title: string;
  }[];
}

export interface KAnswer {
  outcome: "answered" | "dont_know" | "search_only";
  answer: string | null;
  reason: string | null;
  confidence: "high" | "medium" | null;
  contains_unverified_sources: boolean;
  citations: KCitation[];
  can_ask_expert: boolean;
}

export interface KItemSummary {
  id: string;
  title: string;
  status: string;
  origin: string;
  ai_extracted: boolean;
  department_id: string | null;
  sensitivity: number;
  owner_person_id: string | null;
  usage_count: number;
  verified_at: string | null;
  stale_after: string | null;
  updated_at: string;
}

export interface KItemDetail {
  id: string;
  title: string;
  status: string;
  origin: string;
  ai_extracted: boolean;
  department_id: string | null;
  sensitivity: number;
  owner_person_id: string | null;
  usage_count: number;
  verified_at: string | null;
  stale_after: string | null;
  updated_at: string;
  body: string;
  self_verified: boolean;
  versions: Array<{
    version_no: number;
    change_kind: string;
    author_person_id: string | null;
    created_at: string;
    erased_at: string | null;
    current: boolean;
  }>;
  provenance: Array<{
    source_id: string;
    title: string;
    page_from: number | null;
    page_to: number | null;
  }>;
}

export interface KVersionCreated {
  id: string;
  status: string;
  version_no: number;
}

export interface KCount {
  count: number;
}

export interface KRestricted {
  id: string;
  sensitivity: number;
}

export interface KInterview {
  id: string;
  expert_person_id: string;
  job_role: string;
  status: string;
  turn_count: number;
  max_turns: number;
  created_at: string;
  last_turn_at: string | null;
  completed_at: string | null;
}

export interface KInterviewDetail {
  id: string;
  expert_person_id: string;
  job_role: string;
  status: string;
  turn_count: number;
  max_turns: number;
  created_at: string;
  last_turn_at: string | null;
  completed_at: string | null;
  turns: Array<{
    ordinal: number;
    topic_id: string | null;
    question: string;
    kind: string;
    answer: string | null;
    answered_at: string | null;
    erased: boolean;
  }>;
}

export interface KTurn {
  interview_id: string;
  status: string;
  next_question: string | null;
  turn_count: number;
  candidate_item_id: string | null;
}

export interface KGapReport {
  job_role: string;
  topics: Array<{
    topic_id: string;
    name: string;
    required: boolean;
    importance: number;
    label: "uncovered" | "unverified" | "single_source" | "stale" | "thin" | "covered";
    verified_items: number;
    contributors: number;
  }>;
}

export interface KTopic {
  id: string;
  name: string;
  description: string;
  department_id: string | null;
  sensitivity: number;
  origin: string;
  status: string;
  created_at: string;
}

export interface KRoleTopics {
  job_role: string;
  topics: {
    topic_id: string;
    required: boolean;
    importance: number;
  }[];
}

export interface KRolePeople {
  job_role: string;
  people: {
    person_id: string;
    relation: string;
  }[];
}

export interface KProposed {
  proposed: string[];
}

export interface KExpertQuestionCreated {
  id: string;
  status: string;
  expires_at: string;
}

export interface KExpertQuestion {
  id: string;
  question: string;
  expert_person_id: string;
  status: string;
  decline_reason: string | null;
  answer_item_id: string | null;
  created_at: string;
  answered_at: string | null;
  expires_at: string;
}

export interface KExpertReply {
  id: string;
  status: string;
  answer_item_id: string;
}

export interface KGenerated {
  created: string[];
  refused: {
    item_id: string;
    reason: string;
  }[];
}

export interface KQuizItem {
  id: string;
  topic_id: string | null;
  knowledge_item_id: string;
  kind: string;
  stem: string;
  options: string[] | null;
  correct_option: number | null;
  rubric: string[] | null;
  status: string;
  approved_at: string | null;
  created_at: string;
}

export interface KAttemptStarted {
  id: string;
  expires_at: string;
  questions: Array<{
    position: number;
    kind: string;
    stem: string;
    options: string[] | null;
  }>;
}

export interface KAttempt {
  id: string;
  learner_person_id: string;
  job_role: string;
  status: string;
  started_at: string;
  expires_at: string;
  submitted_at: string | null;
  graded_at: string | null;
  bank_size: number;
  questions: Array<{
    answer_id: string;
    position: number;
    kind: string;
    stem: string;
    options: string[] | null;
    chosen_option: number | null;
    answer_text: string | null;
    final_score: number | null;
    decided_by: string | null;
    correct_option?: number;
  }>;
}

export interface KAnswerSaved {
  id: string;
  position: number;
}

export interface KReport {
  attempt_id: string;
  learner_person_id: string;
  job_role: string;
  status: string;
  started_at: string;
  submitted_at: string | null;
  graded_at: string | null;
  bank_size: number;
  statement: string;
  topics: Array<{
    topic_id: string;
    name: string;
    score: number | null;
    note: string | null;
    questions_asked: number;
    questions_in_bank: number;
    ai_graded: number;
    person_graded: number;
  }>;
  coverage_gaps: {
    topic_id: string;
    name: string;
    gap: string;
  }[];
}

export interface KConsent {
  id: string;
  person_id: string;
  scope: string;
  purpose: string;
  policy_version: string;
  granted_at: string;
  expires_at: string | null;
  superseded_at: string | null;
  withdrawn_at: string | null;
  withdrawal_status: string;
  legal_hold: boolean;
}

export interface KWithdrawalsForPerson {
  person_id: string;
  withdrawals: {
    consent_id: string;
    withdrawal_status: string;
  }[];
}

export interface KTask {
  id: string;
  kind: string;
  subject_type: string;
  subject_id: string;
  department_id: string | null;
  sensitivity: number;
  priority: number;
  status: string;
  assigned_to_card_id: string | null;
  created_at: string;
  due_at: string;
  first_response_at: string | null;
  resolved_at: string | null;
  resolution: string | null;
}

export interface KBulkResult {
  results: Array<{
    task_id: string;
    outcome: "done" | "forbidden" | "not_found" | "refused";
  }>;
}

export interface KAllowTerm {
  id: string;
  term: string;
  entity_type: string;
  created_at: string;
}

export interface KSettings {
  chunk_quota: number;
  max_upload_bytes: number;
  max_pdf_pages: number;
  second_reviewer_required: boolean;
  verifications_per_hour: number;
  verifications_per_day: number;
  learner_sources: "verified_only" | "all_marked";
  stale_after_days: number;
  review_sla_days: number;
  answer_log_retention_days: number;
  quiz_answer_retention_days: number;
  interview_max_turns: number;
  interview_max_cost_micro_usd: number;
  expert_question_expiry_days: number;
  quiz_questions_per_attempt: number;
  quiz_time_limit_minutes: number;
  quiz_min_questions_per_topic: number;
  quiz_show_answers_after_grading: boolean;
}

export interface KAiBudget {
  period: string;
  monthly_cap_micro_usd: number;
  spent_micro_usd: number;
  reserved_micro_usd: number;
  calls: number;
  ai_stopped: boolean;
}

export interface KTenantAiBudget {
  tenant_id: string;
  monthly_cap_micro_usd: number;
}

export interface KKillSwitch {
  on: boolean;
  reason: string | null;
}

export interface KStorage {
  database_bytes: number;
  total_chunks: number;
  companies: {
    tenant_id: string;
    chunk_count: number;
  }[];
}

export interface Problem {
  type: string;
  title: string;
  status: number;
  request_id: string;
  detail?: string;
  errors?: {
    path: string;
    message: string;
  }[];
}

export interface Health {
  status: "ok";
  version: string;
}

export interface Ready {
  status: "ready" | "not_ready";
  checks: {
    database: boolean;
    migrations: boolean;
    config: boolean;
  };
}

export interface LoginBeginRequest {
  card_number: string;
}

export interface LoginBeginResponse {
  login_txn: string;
  webauthn_options: {
    [key: string]: unknown;
  };
  totp_allowed: true;
  expires_in: number;
}

export interface LoginVerifyRequest {
  login_txn: string;
  sc: string;
  factor: {
    type: "passkey";
    assertion: {
      [key: string]: unknown;
    };
  } | {
    type: "totp";
    code: string;
  };
}

export interface Session {
  card_id: string;
  tenant_id: string;
  person_id: string | null;
  card_number_masked: string;
  roles: Array<"company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor">;
  permissions: string[];
  card_state: "issued" | "active" | "suspended" | "revoked" | "expired" | "replaced";
  read_only: boolean;
  export_only: boolean;
  expires_at: string;
  grace_until: string;
  renewal_due: string;
  session_idle_expires_at: string;
  session_absolute_expires_at: string;
  csrf_token: string;
}

export interface EnrollmentBeginRequest {
  card_number: string;
  sc: string;
  enrollment_token: string;
  factor_type: "passkey" | "totp";
  label?: string;
}

export interface EnrollmentBeginResponse {
  enrollment_txn: string;
  factor_type: "passkey" | "totp";
  webauthn_options?: {
    [key: string]: unknown;
  };
  totp?: {
    secret: string;
    otpauth_uri: string;
  };
}

export interface EnrollmentCompleteRequest {
  enrollment_txn: string;
  attestation?: {
    [key: string]: unknown;
  };
  totp_code?: string;
}

export interface Credential {
  id: string;
  type: "passkey" | "totp";
  label: string;
  created_at: string;
  last_used_at: string | null;
}

export interface RoleAssignmentInput {
  role_key: "company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor";
  department_id?: string | null;
}

export interface RoleAssignment {
  role_key: "company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor";
  department_id: string | null;
  assigned_at: string;
}

export interface Role {
  role_key: "company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor";
  display_name: string;
  rank: number;
  enabled_for_tenant: boolean;
  permissions: Array<{
    permission_key: string;
    scope: "tenant" | "department" | "own";
  }>;
}

export interface Card {
  id: string;
  kind: "person" | "company";
  card_number: string;
  state: "issued" | "active" | "suspended" | "revoked" | "expired" | "replaced";
  person_id: string | null;
  issued_at: string;
  activated_at: string | null;
  expires_at: string;
  grace_until: string;
  renewal_due: string;
  renewal_count: number;
  locked: boolean;
  replaced_by_card_id: string | null;
  replaces_card_id: string | null;
  roles: RoleAssignment[];
}

export interface CardWithSecrets {
  card: Card;
  sc?: string;
  enrollment_token?: string;
  enrollment_token_expires_at?: string;
  secret_already_shown: boolean;
}

export interface IssueCardRequest {
  person_id: string;
  roles: RoleAssignmentInput[];
}

export interface ReasonRequest {
  reason: string;
}

export interface ReplaceCardRequest {
  reason: "lost" | "damaged" | "compromised";
  reset_credentials?: boolean;
}

export interface RenewCardRequest {
  validity_days?: number;
}

export type OwnerRecoveryRequest = Record<string, unknown> | Record<string, unknown>;

export interface OwnerRecoveryResult {
  card: Card;
  sc?: string;
  enrollment_token?: string;
  enrollment_token_expires_at?: string;
  secret_already_shown: boolean;
  notified_owner_count: number;
}

export interface EnrollmentTokenRequest {
  revoke_existing?: boolean;
}

export interface EnrollmentTokenResponse {
  enrollment_token?: string;
  enrollment_token_expires_at?: string;
  secret_already_shown: boolean;
}

export interface CardEvent {
  id: string;
  card_id: string;
  occurred_at: string;
  event_type: string;
  actor_card_id: string | null;
  credential_id: string | null;
  device: string | null;
  request_id: string | null;
  metadata: {
    [key: string]: unknown;
  };
}

export type Restriction = ({
  type: "usage_cap";
  enabled: boolean;
  config: {
    limit_key: "requests" | "writes" | "exports";
    window_seconds: number;
    max_count: number;
  };
}) | {
  type: "time_window";
  enabled: boolean;
  config: {
    timezone: string;
    days: number[];
    start: string;
    end: string;
  };
} | {
  type: "network_allowlist";
  enabled: boolean;
  config: {
    cidrs: string[];
  };
} | {
  type: "read_only";
  enabled: boolean;
  config: Record<string, never>;
};

export interface PutCardRestrictionsRequest {
  restrictions: Restriction[];
}

export interface CardRestrictions {
  items: Restriction[];
  counters: {
    limit_key: string;
    window_start: string;
    count: number;
  }[];
}

export interface Person {
  id: string;
  display_name: string;
  email: string | null;
  department_id: string | null;
  status: "active" | "departed";
  created_at: string;
}

export interface CreatePersonRequest {
  display_name: string;
  email?: string | null;
  department_id?: string | null;
}

export interface UpdatePersonRequest {
  display_name?: string;
  email?: string | null;
  department_id?: string | null;
  status?: "active" | "departed";
}

export interface Department {
  id: string;
  name: string;
  created_at: string;
}

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  status: "active" | "suspended" | "closed";
  plan_code: string;
  region: string;
  created_at: string;
}

export interface CreateTenantRequest {
  name: string;
  slug: string;
  owner_display_name: string;
  owner_email?: string | null;
}

export interface TenantCreated {
  tenant: Tenant;
  owner_person: Person;
  company_card: CardWithSecrets;
  owner_card: CardWithSecrets;
}

export interface TenantSettings {
  card_validity_days: number;
  grace_days: number;
  renewal_notice_days: number;
  sc_lockout_threshold: number;
  session_idle_minutes: number;
  session_absolute_hours: number;
  enabled_roles: Array<"company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor">;
  pilot_reviewer_grant: boolean;
  allowed_factor_types: Array<"passkey" | "totp">;
}

export interface UpdateTenantSettingsRequest {
  card_validity_days?: number;
  grace_days?: number;
  renewal_notice_days?: number;
  sc_lockout_threshold?: number;
  session_idle_minutes?: number;
  session_absolute_hours?: number;
  enabled_roles?: Array<"company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor">;
  pilot_reviewer_grant?: boolean;
  allowed_factor_types?: Array<"passkey" | "totp">;
}

export interface TenantUsage {
  cards_by_state: {
    [key: string]: number;
  };
  people: number;
  active_sessions: number;
  cards_expiring_soon: number;
  audit_rows: number;
  logins_last_30_days: number;
  cards_able_to_unlock: number;
  plan: {
    plan_code: string;
    max_person_cards: number | null;
    max_admin_cards: number | null;
  };
}

export interface AuditEvent {
  seq: number;
  occurred_at: string;
  actor_card_id: string | null;
  actor_kind: "card" | "system" | "anonymous" | "service" | "operator";
  action: string;
  resource_type: string | null;
  resource_id: string | null;
  decision: "allow" | "deny" | "event";
  reason_code: string;
  request_id: string | null;
  ip: string | null;
  details: {
    [key: string]: unknown;
  };
  prev_hash: string;
  row_hash: string;
}

export interface AuditVerifyResult {
  ok: boolean;
  complete: boolean;
  rows_checked: number;
  head_seq: number;
  head_hash: string | null;
  first_broken_seq: number | null;
  broken_reason: string | null;
  last_anchor: {
    seq: number;
    anchored_at: string;
    matches: boolean;
  } | null;
}

export interface ExportJob {
  id: string;
  status: "queued" | "running" | "done" | "failed";
  format: string;
  manifest: {
    [key: string]: unknown;
  } | null;
  created_at: string;
  completed_at: string | null;
}

export const operations = {
  getHealth: { method: "GET", path: "/v1/health", status: 200, idempotent: false, public: true, permission: null, contentTypes: [] },
  getReady: { method: "GET", path: "/v1/ready", status: 200, idempotent: false, public: true, permission: null, contentTypes: [] },
  loginBegin: { method: "POST", path: "/v1/auth/login/begin", status: 200, idempotent: false, public: true, permission: null, contentTypes: ["application/json"] },
  loginVerify: { method: "POST", path: "/v1/auth/login/verify", status: 200, idempotent: false, public: true, permission: null, contentTypes: ["application/json"] },
  enrollmentBegin: { method: "POST", path: "/v1/auth/enrollment/begin", status: 200, idempotent: false, public: true, permission: null, contentTypes: ["application/json"] },
  enrollmentComplete: { method: "POST", path: "/v1/auth/enrollment/complete", status: 204, idempotent: false, public: true, permission: null, contentTypes: ["application/json"] },
  getSession: { method: "GET", path: "/v1/auth/session", status: 200, idempotent: false, public: false, permission: "self:read", contentTypes: [] },
  logout: { method: "POST", path: "/v1/auth/logout", status: 204, idempotent: false, public: false, permission: "self:logout", contentTypes: [] },
  listOwnCredentials: { method: "GET", path: "/v1/auth/credentials", status: 200, idempotent: false, public: false, permission: "self:read", contentTypes: [] },
  removeOwnCredential: { method: "DELETE", path: "/v1/auth/credentials/{credential_id}", status: 204, idempotent: false, public: false, permission: "self:credential_remove", contentTypes: [] },
  issueCard: { method: "POST", path: "/v1/cards", status: 201, idempotent: true, public: false, permission: "card:issue", contentTypes: ["application/json"] },
  listCards: { method: "GET", path: "/v1/cards", status: 200, idempotent: false, public: false, permission: "card:list", contentTypes: [] },
  getCard: { method: "GET", path: "/v1/cards/{card_id}", status: 200, idempotent: false, public: false, permission: "card:read", contentTypes: [] },
  suspendCard: { method: "POST", path: "/v1/cards/{card_id}/suspend", status: 200, idempotent: true, public: false, permission: "card:suspend", contentTypes: ["application/json"] },
  reinstateCard: { method: "POST", path: "/v1/cards/{card_id}/reinstate", status: 200, idempotent: true, public: false, permission: "card:reinstate", contentTypes: [] },
  revokeCard: { method: "POST", path: "/v1/cards/{card_id}/revoke", status: 200, idempotent: true, public: false, permission: "card:revoke", contentTypes: ["application/json"] },
  replaceCard: { method: "POST", path: "/v1/cards/{card_id}/replace", status: 201, idempotent: true, public: false, permission: "card:replace", contentTypes: ["application/json"] },
  renewCard: { method: "POST", path: "/v1/cards/{card_id}/renew", status: 200, idempotent: true, public: false, permission: "card:renew", contentTypes: ["application/json"] },
  unlockCard: { method: "POST", path: "/v1/cards/{card_id}/unlock", status: 200, idempotent: true, public: false, permission: "card:unlock", contentTypes: [] },
  issueEnrollmentToken: { method: "POST", path: "/v1/cards/{card_id}/enrollment-token", status: 201, idempotent: true, public: false, permission: "card:reset_credentials", contentTypes: ["application/json"] },
  listCardEvents: { method: "GET", path: "/v1/cards/{card_id}/events", status: 200, idempotent: false, public: false, permission: "card_events:read", contentTypes: [] },
  getCardRestrictions: { method: "GET", path: "/v1/cards/{card_id}/restrictions", status: 200, idempotent: false, public: false, permission: "card_restrictions:read", contentTypes: [] },
  putCardRestrictions: { method: "PUT", path: "/v1/cards/{card_id}/restrictions", status: 200, idempotent: true, public: false, permission: "card_restrictions:update", contentTypes: ["application/json"] },
  listRoles: { method: "GET", path: "/v1/roles", status: 200, idempotent: false, public: false, permission: "role:read", contentTypes: [] },
  listCardRoles: { method: "GET", path: "/v1/cards/{card_id}/roles", status: 200, idempotent: false, public: false, permission: "card_roles:read", contentTypes: [] },
  assignCardRole: { method: "POST", path: "/v1/cards/{card_id}/roles", status: 201, idempotent: true, public: false, permission: "card_roles:assign", contentTypes: ["application/json"] },
  replaceCardRoles: { method: "PUT", path: "/v1/cards/{card_id}/roles", status: 200, idempotent: true, public: false, permission: "card_roles:assign", contentTypes: ["application/json"] },
  removeCardRole: { method: "DELETE", path: "/v1/cards/{card_id}/roles/{role_key}", status: 204, idempotent: true, public: false, permission: "card_roles:remove", contentTypes: [] },
  createPerson: { method: "POST", path: "/v1/people", status: 201, idempotent: true, public: false, permission: "person:create", contentTypes: ["application/json"] },
  listPeople: { method: "GET", path: "/v1/people", status: 200, idempotent: false, public: false, permission: "person:read", contentTypes: [] },
  getPerson: { method: "GET", path: "/v1/people/{person_id}", status: 200, idempotent: false, public: false, permission: "person:read", contentTypes: [] },
  updatePerson: { method: "PATCH", path: "/v1/people/{person_id}", status: 200, idempotent: true, public: false, permission: "person:update", contentTypes: ["application/json"] },
  createDepartment: { method: "POST", path: "/v1/departments", status: 201, idempotent: true, public: false, permission: "department:create", contentTypes: ["application/json"] },
  listDepartments: { method: "GET", path: "/v1/departments", status: 200, idempotent: false, public: false, permission: "department:read", contentTypes: [] },
  createTenant: { method: "POST", path: "/v1/tenants", status: 201, idempotent: true, public: false, permission: "tenant:create", contentTypes: ["application/json"] },
  listTenants: { method: "GET", path: "/v1/tenants", status: 200, idempotent: false, public: false, permission: "tenant:list", contentTypes: [] },
  renewCompanyCard: { method: "POST", path: "/v1/tenants/{tenant_id}/company-card/renew", status: 200, idempotent: true, public: false, permission: "tenant:renew_company_card", contentTypes: ["application/json"] },
  recoverOwnerCard: { method: "POST", path: "/v1/tenants/{tenant_id}/owner-recovery", status: 201, idempotent: true, public: false, permission: "tenant:recover_owner", contentTypes: ["application/json"] },
  getCurrentTenant: { method: "GET", path: "/v1/tenants/current", status: 200, idempotent: false, public: false, permission: "tenant:read", contentTypes: [] },
  getTenantSettings: { method: "GET", path: "/v1/tenants/current/settings", status: 200, idempotent: false, public: false, permission: "tenant_settings:read", contentTypes: [] },
  updateTenantSettings: { method: "PATCH", path: "/v1/tenants/current/settings", status: 200, idempotent: true, public: false, permission: "tenant_settings:update", contentTypes: ["application/json"] },
  getTenantUsage: { method: "GET", path: "/v1/tenants/current/usage", status: 200, idempotent: false, public: false, permission: "tenant_usage:read", contentTypes: [] },
  listAuditEvents: { method: "GET", path: "/v1/audit/events", status: 200, idempotent: false, public: false, permission: "audit:read", contentTypes: [] },
  verifyAuditChain: { method: "POST", path: "/v1/audit/verify", status: 200, idempotent: false, public: false, permission: "audit:verify", contentTypes: ["application/json"] },
  createExport: { method: "POST", path: "/v1/exports", status: 202, idempotent: true, public: false, permission: "export:create", contentTypes: [] },
  getExport: { method: "GET", path: "/v1/exports/{export_id}", status: 200, idempotent: false, public: false, permission: "export:read", contentTypes: [] },
  createSource: { method: "POST", path: "/v1/sources", status: 201, idempotent: true, public: false, permission: "capture:upload", contentTypes: ["application/json"] },
  listSources: { method: "GET", path: "/v1/sources", status: 200, idempotent: false, public: false, permission: "source:read", contentTypes: [] },
  uploadSourceContent: { method: "PUT", path: "/v1/sources/{source_id}/content", status: 200, idempotent: false, public: false, permission: "capture:upload", contentTypes: ["text/plain","text/markdown","application/pdf"] },
  getSource: { method: "GET", path: "/v1/sources/{source_id}", status: 200, idempotent: false, public: false, permission: "source:read", contentTypes: [] },
  confirmSource: { method: "POST", path: "/v1/sources/{source_id}/confirm", status: 200, idempotent: true, public: false, permission: "source:confirm", contentTypes: [] },
  withdrawSource: { method: "POST", path: "/v1/sources/{source_id}/withdraw", status: 200, idempotent: true, public: false, permission: "source:withdraw", contentTypes: [] },
  setSourceLabels: { method: "PATCH", path: "/v1/sources/{source_id}/labels", status: 200, idempotent: true, public: false, permission: "knowledge:label", contentTypes: ["application/json"] },
  askKnowledge: { method: "POST", path: "/v1/knowledge/ask", status: 200, idempotent: false, public: false, permission: "knowledge:ask", contentTypes: ["application/json"] },
  listKnowledgeItems: { method: "GET", path: "/v1/knowledge/items", status: 200, idempotent: false, public: false, permission: "knowledge:read", contentTypes: [] },
  createKnowledgeItem: { method: "POST", path: "/v1/knowledge/items", status: 201, idempotent: true, public: false, permission: "knowledge:contribute", contentTypes: ["application/json"] },
  getKnowledgeItem: { method: "GET", path: "/v1/knowledge/items/{item_id}", status: 200, idempotent: false, public: false, permission: "knowledge:read", contentTypes: [] },
  proposeItemVersion: { method: "POST", path: "/v1/knowledge/items/{item_id}/versions", status: 201, idempotent: true, public: false, permission: "knowledge:verify", contentTypes: ["application/json"] },
  submitKnowledgeItem: { method: "POST", path: "/v1/knowledge/items/{item_id}/submit", status: 200, idempotent: true, public: false, permission: "knowledge:contribute", contentTypes: [] },
  verifyKnowledgeItem: { method: "POST", path: "/v1/knowledge/items/{item_id}/verify", status: 200, idempotent: true, public: false, permission: "knowledge:verify", contentTypes: [] },
  rejectKnowledgeItem: { method: "POST", path: "/v1/knowledge/items/{item_id}/reject", status: 200, idempotent: true, public: false, permission: "knowledge:verify", contentTypes: [] },
  reopenKnowledgeItem: { method: "POST", path: "/v1/knowledge/items/{item_id}/reopen", status: 200, idempotent: true, public: false, permission: "knowledge:verify", contentTypes: ["application/json"] },
  retireKnowledgeItem: { method: "POST", path: "/v1/knowledge/items/{item_id}/retire", status: 200, idempotent: true, public: false, permission: "knowledge:verify", contentTypes: [] },
  setItemLabels: { method: "PATCH", path: "/v1/knowledge/items/{item_id}/labels", status: 200, idempotent: true, public: false, permission: "knowledge:label", contentTypes: ["application/json"] },
  revertVerifications: { method: "POST", path: "/v1/knowledge/verifications/revert", status: 200, idempotent: true, public: false, permission: "knowledge:revert", contentTypes: ["application/json"] },
  listMyContributions: { method: "GET", path: "/v1/me/contributions", status: 200, idempotent: false, public: false, permission: "knowledge:read", contentTypes: [] },
  restrictContribution: { method: "POST", path: "/v1/me/contributions/{item_id}/restrict", status: 200, idempotent: true, public: false, permission: "contribution:restrict", contentTypes: ["application/json"] },
  createInterview: { method: "POST", path: "/v1/interviews", status: 201, idempotent: true, public: false, permission: "interview:manage", contentTypes: ["application/json"] },
  listInterviews: { method: "GET", path: "/v1/interviews", status: 200, idempotent: false, public: false, permission: "interview:read", contentTypes: [] },
  getInterview: { method: "GET", path: "/v1/interviews/{interview_id}", status: 200, idempotent: false, public: false, permission: "interview:read", contentTypes: [] },
  acceptInterview: { method: "POST", path: "/v1/interviews/{interview_id}/accept", status: 200, idempotent: true, public: false, permission: "capture:interview", contentTypes: [] },
  answerInterviewTurn: { method: "POST", path: "/v1/interviews/{interview_id}/turns", status: 200, idempotent: true, public: false, permission: "capture:interview", contentTypes: ["application/json"] },
  pauseInterview: { method: "POST", path: "/v1/interviews/{interview_id}/pause", status: 200, idempotent: true, public: false, permission: "capture:interview", contentTypes: [] },
  resumeInterview: { method: "POST", path: "/v1/interviews/{interview_id}/resume", status: 200, idempotent: true, public: false, permission: "capture:interview", contentTypes: [] },
  completeInterview: { method: "POST", path: "/v1/interviews/{interview_id}/complete", status: 200, idempotent: true, public: false, permission: "capture:interview", contentTypes: [] },
  getGapReport: { method: "GET", path: "/v1/gaps", status: 200, idempotent: false, public: false, permission: "gap:read", contentTypes: [] },
  listTopics: { method: "GET", path: "/v1/topics", status: 200, idempotent: false, public: false, permission: "topic:read", contentTypes: [] },
  createTopic: { method: "POST", path: "/v1/topics", status: 201, idempotent: true, public: false, permission: "topic:manage", contentTypes: ["application/json"] },
  updateTopic: { method: "PATCH", path: "/v1/topics/{topic_id}", status: 200, idempotent: true, public: false, permission: "topic:manage", contentTypes: ["application/json"] },
  setRoleTopics: { method: "PUT", path: "/v1/job-roles/{job_role}/topics", status: 200, idempotent: true, public: false, permission: "topic:manage", contentTypes: ["application/json"] },
  setRolePeople: { method: "PUT", path: "/v1/job-roles/{job_role}/people", status: 200, idempotent: true, public: false, permission: "topic:manage", contentTypes: ["application/json"] },
  suggestTopics: { method: "POST", path: "/v1/topics/suggest", status: 201, idempotent: true, public: false, permission: "topic:manage", contentTypes: ["application/json"] },
  createExpertQuestion: { method: "POST", path: "/v1/expert-questions", status: 201, idempotent: true, public: false, permission: "expert_question:create", contentTypes: ["application/json"] },
  listExpertQuestions: { method: "GET", path: "/v1/expert-questions", status: 200, idempotent: false, public: false, permission: "expert_question:read", contentTypes: [] },
  replyExpertQuestion: { method: "POST", path: "/v1/expert-questions/{question_id}/reply", status: 200, idempotent: true, public: false, permission: "expert_question:answer", contentTypes: ["application/json"] },
  declineExpertQuestion: { method: "POST", path: "/v1/expert-questions/{question_id}/decline", status: 200, idempotent: true, public: false, permission: "expert_question:answer", contentTypes: ["application/json"] },
  generateQuizQuestions: { method: "POST", path: "/v1/readiness/questions/generate", status: 201, idempotent: true, public: false, permission: "quiz:manage", contentTypes: ["application/json"] },
  listQuizQuestions: { method: "GET", path: "/v1/readiness/questions", status: 200, idempotent: false, public: false, permission: "quiz:read", contentTypes: [] },
  editQuizQuestion: { method: "PATCH", path: "/v1/readiness/questions/{question_id}", status: 200, idempotent: true, public: false, permission: "quiz:manage", contentTypes: ["application/json"] },
  approveQuizQuestion: { method: "POST", path: "/v1/readiness/questions/{question_id}/approve", status: 200, idempotent: true, public: false, permission: "quiz:manage", contentTypes: [] },
  retireQuizQuestion: { method: "POST", path: "/v1/readiness/questions/{question_id}/retire", status: 200, idempotent: true, public: false, permission: "quiz:manage", contentTypes: [] },
  startReadinessAttempt: { method: "POST", path: "/v1/readiness/attempts", status: 201, idempotent: true, public: false, permission: "quiz:take", contentTypes: ["application/json"] },
  getReadinessAttempt: { method: "GET", path: "/v1/readiness/attempts/{attempt_id}", status: 200, idempotent: false, public: false, permission: "quiz:read_results", contentTypes: [] },
  saveAttemptAnswer: { method: "POST", path: "/v1/readiness/attempts/{attempt_id}/answers", status: 200, idempotent: true, public: false, permission: "quiz:take", contentTypes: ["application/json"] },
  submitReadinessAttempt: { method: "POST", path: "/v1/readiness/attempts/{attempt_id}/submit", status: 200, idempotent: true, public: false, permission: "quiz:take", contentTypes: [] },
  overrideQuizAnswer: { method: "POST", path: "/v1/readiness/answers/{answer_id}/override", status: 200, idempotent: true, public: false, permission: "quiz:grade", contentTypes: ["application/json"] },
  getReadinessReport: { method: "GET", path: "/v1/readiness/reports/{attempt_id}", status: 200, idempotent: false, public: false, permission: "quiz:read_results", contentTypes: [] },
  listConsents: { method: "GET", path: "/v1/consents", status: 200, idempotent: false, public: false, permission: "consent:read", contentTypes: [] },
  giveConsent: { method: "POST", path: "/v1/consents", status: 201, idempotent: true, public: false, permission: "consent:give", contentTypes: ["application/json"] },
  listMyConsents: { method: "GET", path: "/v1/me/consents", status: 200, idempotent: false, public: false, permission: "consent:give", contentTypes: [] },
  withdrawConsent: { method: "POST", path: "/v1/consents/{consent_id}/withdraw", status: 200, idempotent: true, public: false, permission: "consent:withdraw", contentTypes: [] },
  recordWithdrawalForPerson: { method: "POST", path: "/v1/people/{person_id}/consent-withdrawals", status: 200, idempotent: true, public: false, permission: "consent:hold", contentTypes: ["application/json"] },
  holdConsent: { method: "POST", path: "/v1/consents/{consent_id}/hold", status: 200, idempotent: true, public: false, permission: "consent:hold", contentTypes: ["application/json"] },
  releaseConsentHold: { method: "POST", path: "/v1/consents/{consent_id}/release-hold", status: 200, idempotent: true, public: false, permission: "consent:hold", contentTypes: [] },
  listReviewTasks: { method: "GET", path: "/v1/review/tasks", status: 200, idempotent: false, public: false, permission: "review:read", contentTypes: [] },
  getReviewTask: { method: "GET", path: "/v1/review/tasks/{task_id}", status: 200, idempotent: false, public: false, permission: "review:read", contentTypes: [] },
  assignReviewTask: { method: "POST", path: "/v1/review/tasks/{task_id}/assign", status: 200, idempotent: true, public: false, permission: "review:resolve", contentTypes: ["application/json"] },
  unassignReviewTask: { method: "POST", path: "/v1/review/tasks/{task_id}/unassign", status: 200, idempotent: true, public: false, permission: "review:resolve", contentTypes: [] },
  dismissReviewTask: { method: "POST", path: "/v1/review/tasks/{task_id}/dismiss", status: 200, idempotent: true, public: false, permission: "review:resolve", contentTypes: [] },
  bulkReviewTasks: { method: "POST", path: "/v1/review/tasks/bulk", status: 200, idempotent: true, public: false, permission: "review:resolve", contentTypes: ["application/json"] },
  listRedactionAllowlist: { method: "GET", path: "/v1/redaction/allowlist", status: 200, idempotent: false, public: false, permission: "review:read", contentTypes: [] },
  addRedactionAllowlistTerm: { method: "POST", path: "/v1/redaction/allowlist", status: 201, idempotent: true, public: false, permission: "redaction:manage", contentTypes: ["application/json"] },
  deleteRedactionAllowlistTerm: { method: "DELETE", path: "/v1/redaction/allowlist/{term_id}", status: 204, idempotent: true, public: false, permission: "redaction:manage", contentTypes: [] },
  getKnowledgeSettings: { method: "GET", path: "/v1/knowledge/settings", status: 200, idempotent: false, public: false, permission: "knowledge_settings:read", contentTypes: [] },
  updateKnowledgeSettings: { method: "PATCH", path: "/v1/knowledge/settings", status: 200, idempotent: true, public: false, permission: "knowledge_settings:update", contentTypes: ["application/json"] },
  getAiBudget: { method: "GET", path: "/v1/ai/budget", status: 200, idempotent: false, public: false, permission: "ai_budget:read", contentTypes: [] },
  setTenantAiBudget: { method: "PUT", path: "/v1/tenants/{tenant_id}/ai-budget", status: 200, idempotent: true, public: false, permission: "ai_budget:manage", contentTypes: ["application/json"] },
  setAiKillSwitch: { method: "PUT", path: "/v1/platform/ai/kill-switch", status: 200, idempotent: true, public: false, permission: "ai_kill_switch:manage", contentTypes: ["application/json"] },
  getPlatformStorage: { method: "GET", path: "/v1/platform/storage", status: 200, idempotent: false, public: false, permission: "platform_storage:read", contentTypes: [] },
} as const;

export type OperationId = keyof typeof operations;

export interface OperationTypes {
  getHealth: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: Health;
  };
  getReady: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: Ready;
  };
  loginBegin: {
    path: undefined;
    query: undefined;
    body: LoginBeginRequest;
    response: LoginBeginResponse;
  };
  loginVerify: {
    path: undefined;
    query: undefined;
    body: LoginVerifyRequest;
    response: Session;
  };
  enrollmentBegin: {
    path: undefined;
    query: undefined;
    body: EnrollmentBeginRequest;
    response: EnrollmentBeginResponse;
  };
  enrollmentComplete: {
    path: undefined;
    query: undefined;
    body: EnrollmentCompleteRequest;
    response: undefined;
  };
  getSession: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: Session;
  };
  logout: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: undefined;
  };
  listOwnCredentials: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: {
      items: Credential[];
    };
  };
  removeOwnCredential: {
    path: { credential_id: string };
    query: undefined;
    body: undefined;
    response: undefined;
  };
  issueCard: {
    path: undefined;
    query: undefined;
    body: IssueCardRequest;
    response: CardWithSecrets;
  };
  listCards: {
    path: undefined;
    query: { limit?: number; cursor?: string; state?: "issued" | "active" | "suspended" | "revoked" | "expired" | "replaced"; kind?: "person" | "company"; person_id?: string };
    body: undefined;
    response: {
      items: Card[];
      next_cursor: string | null;
    };
  };
  getCard: {
    path: { card_id: string };
    query: undefined;
    body: undefined;
    response: Card;
  };
  suspendCard: {
    path: { card_id: string };
    query: undefined;
    body: ReasonRequest;
    response: Card;
  };
  reinstateCard: {
    path: { card_id: string };
    query: undefined;
    body: undefined;
    response: Card;
  };
  revokeCard: {
    path: { card_id: string };
    query: undefined;
    body: ReasonRequest;
    response: Card;
  };
  replaceCard: {
    path: { card_id: string };
    query: undefined;
    body: ReplaceCardRequest;
    response: CardWithSecrets;
  };
  renewCard: {
    path: { card_id: string };
    query: undefined;
    body: RenewCardRequest;
    response: CardWithSecrets;
  };
  unlockCard: {
    path: { card_id: string };
    query: undefined;
    body: undefined;
    response: CardWithSecrets;
  };
  issueEnrollmentToken: {
    path: { card_id: string };
    query: undefined;
    body: EnrollmentTokenRequest;
    response: EnrollmentTokenResponse;
  };
  listCardEvents: {
    path: { card_id: string };
    query: { limit?: number; cursor?: string; event_type?: string };
    body: undefined;
    response: {
      items: CardEvent[];
      next_cursor: string | null;
    };
  };
  getCardRestrictions: {
    path: { card_id: string };
    query: undefined;
    body: undefined;
    response: CardRestrictions;
  };
  putCardRestrictions: {
    path: { card_id: string };
    query: undefined;
    body: PutCardRestrictionsRequest;
    response: CardRestrictions;
  };
  listRoles: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: {
      items: Role[];
    };
  };
  listCardRoles: {
    path: { card_id: string };
    query: undefined;
    body: undefined;
    response: {
      items: RoleAssignment[];
    };
  };
  assignCardRole: {
    path: { card_id: string };
    query: undefined;
    body: RoleAssignmentInput;
    response: RoleAssignment;
  };
  replaceCardRoles: {
    path: { card_id: string };
    query: undefined;
    body: {
      roles: RoleAssignmentInput[];
    };
    response: {
      items: RoleAssignment[];
    };
  };
  removeCardRole: {
    path: { card_id: string; role_key: "company_owner" | "admin" | "department_manager" | "auditor" | "reviewer" | "expert" | "successor" | "contractor" };
    query: undefined;
    body: undefined;
    response: undefined;
  };
  createPerson: {
    path: undefined;
    query: undefined;
    body: CreatePersonRequest;
    response: Person;
  };
  listPeople: {
    path: undefined;
    query: { limit?: number; cursor?: string; department_id?: string; status?: "active" | "departed" };
    body: undefined;
    response: {
      items: Person[];
      next_cursor: string | null;
    };
  };
  getPerson: {
    path: { person_id: string };
    query: undefined;
    body: undefined;
    response: Person;
  };
  updatePerson: {
    path: { person_id: string };
    query: undefined;
    body: UpdatePersonRequest;
    response: Person;
  };
  createDepartment: {
    path: undefined;
    query: undefined;
    body: {
      name: string;
    };
    response: Department;
  };
  listDepartments: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: {
      items: Department[];
    };
  };
  createTenant: {
    path: undefined;
    query: undefined;
    body: CreateTenantRequest;
    response: TenantCreated;
  };
  listTenants: {
    path: undefined;
    query: { limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: Tenant[];
      next_cursor: string | null;
    };
  };
  renewCompanyCard: {
    path: { tenant_id: string };
    query: undefined;
    body: RenewCardRequest;
    response: CardWithSecrets;
  };
  recoverOwnerCard: {
    path: { tenant_id: string };
    query: undefined;
    body: OwnerRecoveryRequest;
    response: OwnerRecoveryResult;
  };
  getCurrentTenant: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: Tenant;
  };
  getTenantSettings: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: TenantSettings;
  };
  updateTenantSettings: {
    path: undefined;
    query: undefined;
    body: UpdateTenantSettingsRequest;
    response: TenantSettings;
  };
  getTenantUsage: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: TenantUsage;
  };
  listAuditEvents: {
    path: undefined;
    query: { limit?: number; cursor?: string; actor_card_id?: string; action?: string; resource_type?: string; resource_id?: string; decision?: "allow" | "deny" | "event" };
    body: undefined;
    response: {
      items: AuditEvent[];
      next_cursor: string | null;
    };
  };
  verifyAuditChain: {
    path: undefined;
    query: undefined;
    body: {
      from_seq?: number;
      to_seq?: number;
    };
    response: AuditVerifyResult;
  };
  createExport: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: ExportJob;
  };
  getExport: {
    path: { export_id: string };
    query: undefined;
    body: undefined;
    response: ExportJob;
  };
  createSource: {
    path: undefined;
    query: undefined;
    body: {
      title: string;
      department_id?: string | null;
      sensitivity?: number;
      contributor_person_id?: string | null;
      company_document?: boolean;
    };
    response: KSourceCreated;
  };
  listSources: {
    path: undefined;
    query: { status?: "awaiting_confirmation" | "awaiting_content" | "processing" | "ready" | "failed"; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KSource[];
      next_cursor: string | null;
    };
  };
  uploadSourceContent: {
    path: { source_id: string };
    query: undefined;
    body: Blob;
    response: KUploadResult;
  };
  getSource: {
    path: { source_id: string };
    query: undefined;
    body: undefined;
    response: KSourceDetail;
  };
  confirmSource: {
    path: { source_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  withdrawSource: {
    path: { source_id: string };
    query: undefined;
    body: undefined;
    response: KSourceWithdrawn;
  };
  setSourceLabels: {
    path: { source_id: string };
    query: undefined;
    body: {
      department_id?: string | null;
      sensitivity: number;
    };
    response: KLabelResult;
  };
  askKnowledge: {
    path: undefined;
    query: undefined;
    body: {
      question: string;
      expert_person_id?: string | null;
    };
    response: KAnswer;
  };
  listKnowledgeItems: {
    path: undefined;
    query: { status?: "candidate" | "in_review" | "verified" | "corrected" | "rejected" | "stale"; mine?: boolean; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KItemSummary[];
      next_cursor: string | null;
    };
  };
  createKnowledgeItem: {
    path: undefined;
    query: undefined;
    body: {
      title: string;
      body: string;
      department_id?: string | null;
      sensitivity?: number;
      contributor_person_id?: string | null;
    };
    response: KStatus;
  };
  getKnowledgeItem: {
    path: { item_id: string };
    query: undefined;
    body: undefined;
    response: KItemDetail;
  };
  proposeItemVersion: {
    path: { item_id: string };
    query: undefined;
    body: {
      body: string;
    };
    response: KVersionCreated;
  };
  submitKnowledgeItem: {
    path: { item_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  verifyKnowledgeItem: {
    path: { item_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  rejectKnowledgeItem: {
    path: { item_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  reopenKnowledgeItem: {
    path: { item_id: string };
    query: undefined;
    body: {
      rollback_to_version?: number;
    };
    response: KStatus;
  };
  retireKnowledgeItem: {
    path: { item_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  setItemLabels: {
    path: { item_id: string };
    query: undefined;
    body: {
      department_id?: string | null;
      sensitivity: number;
    };
    response: KLabelResult;
  };
  revertVerifications: {
    path: undefined;
    query: undefined;
    body: {
      card_id: string;
      since: string;
      until: string;
    };
    response: KCount;
  };
  listMyContributions: {
    path: undefined;
    query: { limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KItemSummary[];
      next_cursor: string | null;
    };
  };
  restrictContribution: {
    path: { item_id: string };
    query: undefined;
    body: {
      sensitivity: number;
    };
    response: KRestricted;
  };
  createInterview: {
    path: undefined;
    query: undefined;
    body: {
      expert_person_id: string;
      job_role: string;
    };
    response: KStatus;
  };
  listInterviews: {
    path: undefined;
    query: { status?: "invited" | "active" | "paused" | "stopped_budget" | "completed" | "abandoned"; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KInterview[];
      next_cursor: string | null;
    };
  };
  getInterview: {
    path: { interview_id: string };
    query: undefined;
    body: undefined;
    response: KInterviewDetail;
  };
  acceptInterview: {
    path: { interview_id: string };
    query: undefined;
    body: undefined;
    response: KTurn;
  };
  answerInterviewTurn: {
    path: { interview_id: string };
    query: undefined;
    body: {
      answer: string;
    };
    response: KTurn;
  };
  pauseInterview: {
    path: { interview_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  resumeInterview: {
    path: { interview_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  completeInterview: {
    path: { interview_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  getGapReport: {
    path: undefined;
    query: { job_role: string };
    body: undefined;
    response: KGapReport;
  };
  listTopics: {
    path: undefined;
    query: { status?: "active" | "proposed" | "retired"; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KTopic[];
      next_cursor: string | null;
    };
  };
  createTopic: {
    path: undefined;
    query: undefined;
    body: {
      name: string;
      description?: string;
      department_id?: string | null;
      sensitivity?: number;
    };
    response: KTopic;
  };
  updateTopic: {
    path: { topic_id: string };
    query: undefined;
    body: {
      name?: string;
      description?: string;
      status?: "active" | "retired";
    };
    response: KTopic;
  };
  setRoleTopics: {
    path: { job_role: string };
    query: undefined;
    body: {
      topics: {
        topic_id: string;
        required?: boolean;
        importance?: number;
      }[];
    };
    response: KRoleTopics;
  };
  setRolePeople: {
    path: { job_role: string };
    query: undefined;
    body: {
      people: Array<{
        person_id: string;
        relation: "holder" | "successor";
      }>;
    };
    response: KRolePeople;
  };
  suggestTopics: {
    path: undefined;
    query: undefined;
    body: {
      source_id: string;
    };
    response: KProposed;
  };
  createExpertQuestion: {
    path: undefined;
    query: undefined;
    body: {
      expert_person_id: string;
      question: string;
      department_id?: string | null;
      sensitivity?: number;
    };
    response: KExpertQuestionCreated;
  };
  listExpertQuestions: {
    path: undefined;
    query: { box?: "asked" | "addressed" | "all"; limit?: number };
    body: undefined;
    response: {
      items: KExpertQuestion[];
      next_cursor: string | null;
    };
  };
  replyExpertQuestion: {
    path: { question_id: string };
    query: undefined;
    body: {
      answer: string;
      title?: string;
    };
    response: KExpertReply;
  };
  declineExpertQuestion: {
    path: { question_id: string };
    query: undefined;
    body: {
      reason: "not_my_area" | "not_allowed_to_share" | "unclear" | "other";
    };
    response: KStatus;
  };
  generateQuizQuestions: {
    path: undefined;
    query: undefined;
    body: {
      kind: "mcq" | "open";
      item_ids: string[];
    };
    response: KGenerated;
  };
  listQuizQuestions: {
    path: undefined;
    query: { status?: "draft" | "approved" | "retired"; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KQuizItem[];
      next_cursor: string | null;
    };
  };
  editQuizQuestion: {
    path: { question_id: string };
    query: undefined;
    body: {
      stem: string;
      options?: string[];
      correct_option?: number;
      rubric?: string[];
    };
    response: KStatus;
  };
  approveQuizQuestion: {
    path: { question_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  retireQuizQuestion: {
    path: { question_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  startReadinessAttempt: {
    path: undefined;
    query: undefined;
    body: {
      job_role: string;
    };
    response: KAttemptStarted;
  };
  getReadinessAttempt: {
    path: { attempt_id: string };
    query: undefined;
    body: undefined;
    response: KAttempt;
  };
  saveAttemptAnswer: {
    path: { attempt_id: string };
    query: undefined;
    body: {
      position: number;
      chosen_option?: number | null;
      answer_text?: string | null;
    };
    response: KAnswerSaved;
  };
  submitReadinessAttempt: {
    path: { attempt_id: string };
    query: undefined;
    body: undefined;
    response: KStatus;
  };
  overrideQuizAnswer: {
    path: { answer_id: string };
    query: undefined;
    body: {
      score: number;
    };
    response: KStatus;
  };
  getReadinessReport: {
    path: { attempt_id: string };
    query: undefined;
    body: undefined;
    response: KReport;
  };
  listConsents: {
    path: undefined;
    query: { person_id?: string; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KConsent[];
      next_cursor: string | null;
    };
  };
  giveConsent: {
    path: undefined;
    query: undefined;
    body: {
      scope: "own_words" | "documents" | "named_expert";
      purpose: string;
      policy_version: string;
      expires_at?: string;
    };
    response: KConsent;
  };
  listMyConsents: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: {
      items: KConsent[];
      next_cursor: string | null;
    };
  };
  withdrawConsent: {
    path: { consent_id: string };
    query: undefined;
    body: undefined;
    response: KConsent;
  };
  recordWithdrawalForPerson: {
    path: { person_id: string };
    query: undefined;
    body: {
      reference: string;
      scope?: "own_words" | "documents" | "named_expert";
    };
    response: KWithdrawalsForPerson;
  };
  holdConsent: {
    path: { consent_id: string };
    query: undefined;
    body: {
      reason: string;
    };
    response: KConsent;
  };
  releaseConsentHold: {
    path: { consent_id: string };
    query: undefined;
    body: undefined;
    response: KConsent;
  };
  listReviewTasks: {
    path: undefined;
    query: { status?: "open" | "assigned" | "resolved" | "dismissed"; kind?: "verify_item" | "redaction_review" | "expert_question" | "quiz_item_approval" | "grading_override" | "stale_item"; limit?: number; cursor?: string };
    body: undefined;
    response: {
      items: KTask[];
      next_cursor: string | null;
    };
  };
  getReviewTask: {
    path: { task_id: string };
    query: undefined;
    body: undefined;
    response: KTask;
  };
  assignReviewTask: {
    path: { task_id: string };
    query: undefined;
    body: {
      card_id?: string;
    };
    response: KTask;
  };
  unassignReviewTask: {
    path: { task_id: string };
    query: undefined;
    body: undefined;
    response: KTask;
  };
  dismissReviewTask: {
    path: { task_id: string };
    query: undefined;
    body: undefined;
    response: KTask;
  };
  bulkReviewTasks: {
    path: undefined;
    query: undefined;
    body: {
      action: "assign" | "dismiss";
      task_ids: string[];
      card_id?: string;
    };
    response: KBulkResult;
  };
  listRedactionAllowlist: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: {
      items: KAllowTerm[];
      next_cursor: string | null;
    };
  };
  addRedactionAllowlistTerm: {
    path: undefined;
    query: undefined;
    body: {
      term: string;
      entity_type: "PERSON" | "LOCATION" | "ORGANIZATION" | "OTHER";
    };
    response: KAllowTerm;
  };
  deleteRedactionAllowlistTerm: {
    path: { term_id: string };
    query: undefined;
    body: undefined;
    response: undefined;
  };
  getKnowledgeSettings: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: KSettings;
  };
  updateKnowledgeSettings: {
    path: undefined;
    query: undefined;
    body: {
      chunk_quota?: number;
      max_upload_bytes?: number;
      max_pdf_pages?: number;
      second_reviewer_required?: boolean;
      verifications_per_hour?: number;
      verifications_per_day?: number;
      learner_sources?: "verified_only" | "all_marked";
      stale_after_days?: number;
      review_sla_days?: number;
      answer_log_retention_days?: number;
      quiz_answer_retention_days?: number;
      interview_max_turns?: number;
      interview_max_cost_micro_usd?: number;
      expert_question_expiry_days?: number;
      quiz_questions_per_attempt?: number;
      quiz_time_limit_minutes?: number;
      quiz_min_questions_per_topic?: number;
      quiz_show_answers_after_grading?: boolean;
    };
    response: KSettings;
  };
  getAiBudget: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: KAiBudget;
  };
  setTenantAiBudget: {
    path: { tenant_id: string };
    query: undefined;
    body: {
      monthly_cap_micro_usd: number;
    };
    response: KTenantAiBudget;
  };
  setAiKillSwitch: {
    path: undefined;
    query: undefined;
    body: {
      on: boolean;
      reason?: string;
    };
    response: KKillSwitch;
  };
  getPlatformStorage: {
    path: undefined;
    query: undefined;
    body: undefined;
    response: KStorage;
  };
}
