#!/usr/bin/env node
// Writes src/api/generated.ts from services/api/openapi.yaml: one TypeScript type per schema, and
// for every operation its method, path, permission, and the types of what goes in and comes out.
// The screens can therefore only call operations that exist, with fields that exist.
//
//   node scripts/generate-api.mjs           write the file
//   node scripts/generate-api.mjs --check   fail if the committed file differs (CI)
//
// Our own small generator instead of openapi-typescript: that package requires TypeScript 5 and the
// repository uses TypeScript 6 (docs/DEPENDENCIES.md). It supports exactly the constructs the
// contract uses and stops with an error on anything else, rather than guessing.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const here = path.dirname(fileURLToPath(import.meta.url));
const contractPath = path.resolve(here, '..', '..', 'services', 'api', 'openapi.yaml');
const outPath = path.resolve(here, '..', 'src', 'api', 'generated.ts');
const doc = parse(readFileSync(contractPath, 'utf8'));

const KNOWN = new Set([
  'type', 'format', 'additionalProperties', 'required', 'properties', 'items', 'enum', 'anyOf', 'oneOf', 'allOf', 'description', 'minimum', 'maximum',
  'maxLength', 'minLength', 'pattern', '$ref', 'const', 'minItems', 'maxItems', 'default', 'uniqueItems', 'title', 'examples', 'example', 'minProperties', 'maxProperties',
]);
const lit = (v) => (v === null ? 'null' : JSON.stringify(v));
const key = (k) => (/^[A-Za-z_][A-Za-z0-9_]*$/.test(k) ? k : JSON.stringify(k));
const refName = (ref) => {
  const m = /^#\/components\/schemas\/([A-Za-z0-9_]+)$/.exec(ref);
  if (!m) throw new Error(`unsupported $ref: ${ref}`);
  return m[1];
};

function typeOf(schema, indent = '') {
  if (schema === true || schema === undefined) return 'unknown';
  if (typeof schema !== 'object' || schema === null) throw new Error(`unsupported schema: ${JSON.stringify(schema)}`);
  for (const k of Object.keys(schema)) if (!KNOWN.has(k)) throw new Error(`unsupported schema keyword "${k}"`);
  if (schema.$ref) return refName(schema.$ref);
  if (schema.const !== undefined) return lit(schema.const);
  if (schema.enum) return schema.enum.map(lit).join(' | ');
  for (const combiner of ['oneOf', 'anyOf']) {
    // "one of these properties must be present": an object with properties whose branches hold only `required`.
    // Each branch becomes the same object with those properties made mandatory.
    if (schema[combiner] && schema.properties && schema[combiner].every((b) => Object.keys(b).length === 1 && Array.isArray(b.required))) {
      const { [combiner]: branches, ...base } = schema;
      return branches.map((b) => typeOf({ ...base, required: [...(base.required ?? []), ...b.required] }, indent)).join(' | ');
    }
    if (schema[combiner]) return schema[combiner].map((s) => typeOf(s, indent)).map((t) => (t.includes(' | ') || t.includes(' & ') ? `(${t})` : t)).join(' | ');
  }
  if (schema.allOf) return schema.allOf.map((s) => typeOf(s, indent)).join(' & ');
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  return types.map((t) => {
    switch (t) {
      case 'string': return schema.format === 'binary' ? 'Blob' : 'string';
      case 'integer': case 'number': return 'number';
      case 'boolean': return 'boolean';
      case 'null': return 'null';
      case 'array': {
        const item = typeOf(schema.items, indent);
        return item.includes(' | ') || item.includes(' & ') ? `Array<${item}>` : `${item}[]`;
      }
      case 'object': case undefined: {
        const props = schema.properties ?? {};
        const required = new Set(schema.required ?? []);
        const inner = `${indent}  `;
        const lines = Object.entries(props).map(([k, v]) => `${inner}${key(k)}${required.has(k) ? '' : '?'}: ${typeOf(v, inner)};`);
        const extra = schema.additionalProperties;
        if (extra !== undefined && extra !== false) lines.push(`${inner}[key: string]: ${extra === true ? 'unknown' : typeOf(extra, inner)};`);
        if (lines.length === 0) return extra === false ? 'Record<string, never>' : 'Record<string, unknown>';
        return `{\n${lines.join('\n')}\n${indent}}`;
      }
      default: throw new Error(`unsupported type "${t}"`);
    }
  }).join(' | ');
}

const out = [
  '// GENERATED by scripts/generate-api.mjs from services/api/openapi.yaml. Do not edit by hand.',
  '// Run `npm run generate` after the contract changes; CI fails if this file is out of date.',
  '/* eslint-disable */',
  '',
];
for (const [name, schema] of Object.entries(doc.components.schemas)) {
  const t = typeOf(schema);
  // an interface only for ONE object; a union of objects ("} | {") is a type alias
  out.push(t.startsWith('{') && !t.includes('} | {') ? `export interface ${name} ${t}` : `export type ${name} = ${t};`, '');
}

const resolveParam = (p) => {
  if (!p.$ref) return p;
  const m = /^#\/components\/parameters\/([A-Za-z0-9_]+)$/.exec(p.$ref);
  if (!m || !doc.components.parameters?.[m[1]]) throw new Error(`unsupported parameter $ref: ${p.$ref}`);
  return doc.components.parameters[m[1]];
};

const table = [];
const types = [];
for (const [route, methods] of Object.entries(doc.paths)) {
  for (const [method, op] of Object.entries(methods)) {
    if (typeof op !== 'object' || op === null || !op.operationId) throw new Error(`path-level keys are not supported: ${route} ${method}`);
    const params = (op.parameters ?? []).map(resolveParam);
    const group = (where) => {
      const list = params.filter((p) => p.in === where);
      if (list.length === 0) return 'undefined';
      return `{ ${list.map((p) => `${key(p.name)}${p.required ? '' : '?'}: ${typeOf(p.schema)}`).join('; ')} }`;
    };
    // The only header parameter the contract has is the Idempotency-Key, on exactly the operations marked x-idempotent.
    const headers = params.filter((p) => p.in !== 'path' && p.in !== 'query');
    const wantsKey = op['x-idempotent'] === true;
    if (headers.some((p) => p.in !== 'header' || p.name !== 'Idempotency-Key') || (headers.length === 1) !== wantsKey) {
      throw new Error(`${op.operationId}: unsupported parameter, or Idempotency-Key and x-idempotent disagree`);
    }
    const content = op.requestBody?.content ?? {};
    const contentTypes = Object.keys(content);
    const json = content['application/json'];
    const body = json ? typeOf(json.schema, '    ') : contentTypes.length > 0 ? 'Blob' : 'undefined';
    const success = Object.entries(op.responses).filter(([code]) => code.startsWith('2'));
    if (success.length !== 1) throw new Error(`${op.operationId}: exactly one success response is supported`);
    const [status, response] = success[0];
    const responseSchema = response.content?.['application/json']?.schema;
    if (response.content && !responseSchema) throw new Error(`${op.operationId}: only JSON responses are supported`);
    table.push(`  ${op.operationId}: { method: ${lit(method.toUpperCase())}, path: ${lit(route)}, status: ${status}, idempotent: ${op['x-idempotent'] === true}, `
      + `public: ${op['x-public'] === true}, permission: ${lit(op['x-permission'] ?? null)}, contentTypes: ${lit(contentTypes)} },`);
    types.push(`  ${op.operationId}: {\n    path: ${group('path')};\n    query: ${group('query')};\n    body: ${body};\n    response: ${responseSchema ? typeOf(responseSchema, '    ') : 'undefined'};\n  };`);
  }
}
out.push('export const operations = {', ...table, '} as const;', '', 'export type OperationId = keyof typeof operations;', '',
  'export interface OperationTypes {', ...types, '}', '');

const text = out.join('\n');
if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(outPath, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    current = '';
  }
  if (current !== text) {
    console.error('api-types: FAIL - src/api/generated.ts does not match services/api/openapi.yaml. Run `npm run generate` in web/ and commit the result.');
    process.exit(1);
  }
  console.log(`api-types: PASS (${table.length} operations, ${Object.keys(doc.components.schemas).length} schemas; generated file matches the contract)`);
} else {
  writeFileSync(outPath, text);
  console.log(`api-types: wrote ${table.length} operations and ${Object.keys(doc.components.schemas).length} schemas`);
}
